update amd-controller

diff --git a/home/ajmasia/bin/amd-controller b/home/ajmasia/bin/amd-controller
--- a/home/ajmasia/bin/amd-controller
+++ b/home/ajmasia/bin/amd-controller
@@ -1,211 +1,211 @@
-# #!/usr/bin/env bash
+#!/usr/bin/env bash
 
-# # AMD Ryzen 7 4800H processor profiler CLI tool for Slimbook computers
-# # If you use different AND processor, please review the params here https://shorturl.at/jHJ35
+# AMD Ryzen 7 4800H processor profiler CLI tool for Slimbook computers
+# If you use different AND processor, please review the params here https://shorturl.at/jHJ35
 
-# COLOR_OFF='\033[0m' # Text Reset
-# GREEN='\033[0;32m'  # Green
-# YELLOW='\033[0;33m' # Yellow
-# RED='\e[31m'        
+COLOR_OFF='\033[0m' # Text Reset
+GREEN='\033[0;32m'  # Green
+YELLOW='\033[0;33m' # Yellow
+RED='\e[31m'        
 
-# CPU=$(cat /proc/cpuinfo | grep name | uniq | cut -d ':' -f2 | sed -r "s/^\s+//g")
-# BAT=0
-# AC_STATUS=0
-# DESKTOP=1
+CPU=$(cat /proc/cpuinfo | grep name | uniq | cut -d ':' -f2 | sed -r "s/^\s+//g")
+BAT=0
+AC_STATUS=0
+DESKTOP=1
 
-# if [ -d "/sys/class/power_supply/BAT0" ]; then
-#   BAT=1 
-#   DESKTOP=0
-#   AC_STATUS=$(cat /sys/class/power_supply/AC0/online)
-# fi
+if [ -d "/sys/class/power_supply/BAT0" ]; then
+  BAT=1 
+  DESKTOP=0
+  AC_STATUS=$(cat /sys/class/power_supply/AC0/online)
+fi
 
-# SLOW_WITH_AC="--tctl-temp=95 --slow-limit=8000 --stapm-limit=8000 --fast-limit=8000"
+SLOW_WITH_AC="--tctl-temp=95 --slow-limit=8000 --stapm-limit=8000 --fast-limit=8000"
 
-# MEDIUM_WITH_AC="--tctl-temp=95 --slow-limit=11000 --stapm-limit=11000 --fast-limit=15000"
+MEDIUM_WITH_AC="--tctl-temp=95 --slow-limit=11000 --stapm-limit=11000 --fast-limit=15000"
 
-# HIGH_WITH_AC="--tctl-temp=95 --slow-limit=25000 --stapm-limit=30000 --fast-limit=35000"
+HIGH_WITH_AC="--tctl-temp=95 --slow-limit=25000 --stapm-limit=30000 --fast-limit=35000"
 
 
-# help() {
-# 	printf "${YELLOW}Slimbook ${CPU} profile updater tool${COLOR_OFF}\n\n"
-# 	printf "${GREEN}Usage amd-controller [command <option>] [option]${COLOR_OFF}\n\n"
+help() {
+	printf "${YELLOW}Slimbook ${CPU} profile updater tool${COLOR_OFF}\n\n"
+	printf "${GREEN}Usage amd-controller [command <option>] [option]${COLOR_OFF}\n\n"
 
-# 	printf "${YELLOW}Commands:${COLOR_OFF}\n"
-# 	echo "set <option>       Set processor profile"
-# 	echo
+	printf "${YELLOW}Commands:${COLOR_OFF}\n"
+	echo "set <option>       Set processor profile"
+	echo
 
-# 	printf "${YELLOW}Options:${COLOR_OFF}\n"
-# 	echo "-s, --slow              Set your processor to work with slow profile"
-# 	echo "-m, --medium            Set your processor to work with medium profile"
-# 	echo "-h, --high              Set your processor to work with high profil"
-# 	echo "-ps, --power-saving     Tune your processor for power saving" 
-# 	echo "-mp, --max-performance  Tune your processor for max performance" 
-# 	echo
+	printf "${YELLOW}Options:${COLOR_OFF}\n"
+	echo "-s, --slow              Set your processor to work with slow profile"
+	echo "-m, --medium            Set your processor to work with medium profile"
+	echo "-h, --high              Set your processor to work with high profil"
+	echo "-ps, --power-saving     Tune your processor for power saving" 
+	echo "-mp, --max-performance  Tune your processor for max performance" 
+	echo
 
-# 	printf "${YELLOW}Flags:${COLOR_OFF}\n"
-# 	echo "-h, --help         Show CLI help"
-# 	echo "-i, --info         Show processor profile info"
-# 	echo
+	printf "${YELLOW}Flags:${COLOR_OFF}\n"
+	echo "-h, --help         Show CLI help"
+	echo "-i, --info         Show processor profile info"
+	echo
 
-# 	printf "${GREEN}Example: Type 'amd-controller set -s' to set your processor to work with a slow profile${COLOR_OFF}\n"
-# 	echo
-# 	echo "Inspired by: https://shorturl.at/hqrAL"
-# 	echo "Review params for other AMD processors here: https://shorturl.at/jHJ35"
-# }
+	printf "${GREEN}Example: Type 'amd-controller set -s' to set your processor to work with a slow profile${COLOR_OFF}\n"
+	echo
+	echo "Inspired by: https://shorturl.at/hqrAL"
+	echo "Review params for other AMD processors here: https://shorturl.at/jHJ35"
+}
 
-# check_dependences() {
-# 	if ! command -v ryzenadj &>/dev/null 2>&1; then
-# 		printf >&2 "${RED}Error: ryzenadj could not be found\n"
-# 		exit 1
-#   elif ! command -v notify-send &>/dev/null 2>&1; then
-# 		printf >&2 "${RED}Error: notify-send could not be found\n"
-# 		exit 1
-#   fi
-# }
+check_dependences() {
+	if ! command -v ryzenadj &>/dev/null 2>&1; then
+		printf >&2 "${RED}Error: ryzenadj could not be found\n"
+		exit 1
+  elif ! command -v notify-send &>/dev/null 2>&1; then
+		printf >&2 "${RED}Error: notify-send could not be found\n"
+		exit 1
+  fi
+}
 
-# set_slow_profile() {
-#   if [[ ($BAT == "1" && $AC_STATUS == "1") || $DESKTOP == "1" ]]; then
-#     sudo ryzenadj $SLOW_WITH_AC &>/dev/null
-#   else
-#     sudo ryzenadj $SLOW_WITH_BATTERY &>/dev/null
-#   fi
+set_slow_profile() {
+  if [[ ($BAT == "1" && $AC_STATUS == "1") || $DESKTOP == "1" ]]; then
+    sudo ryzenadj $SLOW_WITH_AC &>/dev/null
+  else
+    sudo ryzenadj $SLOW_WITH_BATTERY &>/dev/null
+  fi
 
-#   printf "${GREEN}🛠  SLOW profile set successfully for $CPU processor\n"
-# }
+  printf "${GREEN}🛠  SLOW profile set successfully for $CPU processor\n"
+}
 
-# set_medium_profile() {
-#   if [[ ($BAT == "1" && $AC_STATUS == "1") || $DESKTOP == "1" ]]; then
-#     sudo ryzenadj $MEDIUM_WITH_AC &>/dev/null
-#   else
-#     sudo ryzenadj $MEDIUM_WITH_BATTERY &>/dev/null
-#   fi
+set_medium_profile() {
+  if [[ ($BAT == "1" && $AC_STATUS == "1") || $DESKTOP == "1" ]]; then
+    sudo ryzenadj $MEDIUM_WITH_AC &>/dev/null
+  else
+    sudo ryzenadj $MEDIUM_WITH_BATTERY &>/dev/null
+  fi
 
-#   printf "${GREEN}🛠  MEDIUM profile set successfully for $CPU processor\n"
-# }
+  printf "${GREEN}🛠  MEDIUM profile set successfully for $CPU processor\n"
+}
 
-# set_high_profile() {
-#   if [[ ($BAT == "1" && $AC_STATUS == "1") || $DESKTOP == "1" ]]; then
-#     sudo ryzenadj $HIGH_WITH_AC &>/dev/null
-#   else
-#     sudo ryzenadj $HIGH_WITH_BATTERY &>/dev/null
-#   fi
+set_high_profile() {
+  if [[ ($BAT == "1" && $AC_STATUS == "1") || $DESKTOP == "1" ]]; then
+    sudo ryzenadj $HIGH_WITH_AC &>/dev/null
+  else
+    sudo ryzenadj $HIGH_WITH_BATTERY &>/dev/null
+  fi
 
-#   printf "${GREEN}🛠  HIGH profile set successfully for $CPU processor\n"
-# }
+  printf "${GREEN}🛠  HIGH profile set successfully for $CPU processor\n"
+}
 
-# set_fire_profile() {
-#   if [[ ($BAT == "1" && $AC_STATUS == "1") || $DESKTOP == "1" ]]; then
-#     sudo ryzenadj $FIRE_WITH_AC &>/dev/null
-#   else
-#     sudo ryzenadj $FIRE_WITH_BATTERY &>/dev/null
-#   fi
+set_fire_profile() {
+  if [[ ($BAT == "1" && $AC_STATUS == "1") || $DESKTOP == "1" ]]; then
+    sudo ryzenadj $FIRE_WITH_AC &>/dev/null
+  else
+    sudo ryzenadj $FIRE_WITH_BATTERY &>/dev/null
+  fi
 
-#   printf "${GREEN}🛠  FIRE profile set successfully for $CPU processor\n"
-# }
+  printf "${GREEN}🛠  FIRE profile set successfully for $CPU processor\n"
+}
 
-# set_silent_profile() {
-#   if [[ ($BAT == "1" && $AC_STATUS == "1") || $DESKTOP == "1" ]]; then
-#     sudo ryzenadj $SILENT_WITH_AC &>/dev/null
-#   else
-#     sudo ryzenadj $SILENT_WITH_BATTERY  &>/dev/null
-#   fi
+set_silent_profile() {
+  if [[ ($BAT == "1" && $AC_STATUS == "1") || $DESKTOP == "1" ]]; then
+    sudo ryzenadj $SILENT_WITH_AC &>/dev/null
+  else
+    sudo ryzenadj $SILENT_WITH_BATTERY  &>/dev/null
+  fi
 
-#   printf "${GREEN}🛠 SILENT profile set successfully for $CPU processor\n"
-# }
+  printf "${GREEN}🛠 SILENT profile set successfully for $CPU processor\n"
+}
 
-# set_balance_profile() {
-#   if [[ ($BAT == "1" && $AC_STATUS == "1") || $DESKTOP == "1" ]]; then
-#     sudo ryzenadj $BALANCE_WITH_AC &>/dev/null
-#   else
-#     sudo ryzenadj $BALANCE_WITH_BATTERY &>/dev/null
-#   fi
+set_balance_profile() {
+  if [[ ($BAT == "1" && $AC_STATUS == "1") || $DESKTOP == "1" ]]; then
+    sudo ryzenadj $BALANCE_WITH_AC &>/dev/null
+  else
+    sudo ryzenadj $BALANCE_WITH_BATTERY &>/dev/null
+  fi
 
-#   printf "${GREEN}🛠 BALANCE profile set successfully for $CPU processor\n"
-# }
+  printf "${GREEN}🛠 BALANCE profile set successfully for $CPU processor\n"
+}
 
-# set_power_saving_profile() {
-#   sudo ryzenadj --power-saving
+set_power_saving_profile() {
+  sudo ryzenadj --power-saving
 
-#   printf "${GREEN}🛠 POWER SAVING profile set successfullys for $CPU processor\n"
-# }
+  printf "${GREEN}🛠 POWER SAVING profile set successfullys for $CPU processor\n"
+}
 
-# set_max_performance_profile() {
-#   sudo ryzenadj --max-performance
+set_max_performance_profile() {
+  sudo ryzenadj --max-performance
 
-#   printf "${GREEN}🛠 MAX PEPERFORMANCE profile set successfullys for $CPU processor\n"
-# }
+  printf "${GREEN}🛠 MAX PEPERFORMANCE profile set successfullys for $CPU processor\n"
+}
 
-# show_processor_profile_info() {
-#   STAPM_LIMIT=$(sudo ryzenadj -i | grep "STAPM LIMIT" | awk '{print $5}')
-#   PPT_LIMIT_FAST=$(sudo ryzenadj -i | grep "PPT LIMIT FAST" | awk '{print $6}')
-#   PPT_LIMIT_SLOW=$(sudo ryzenadj -i | grep "PPT LIMIT SLOW" | awk '{print $6}')
-#   CCLK_BOOST_SETPOINT=$(sudo ryzenadj -i | grep "CCLK Boost SETPOINT" | awk '{print $6}')
-#   CCLK_BUSY_VALUE=$(sudo ryzenadj -i | grep "CCLK BUSY VALUE" | awk '{print $6}')
+show_processor_profile_info() {
+  STAPM_LIMIT=$(sudo ryzenadj -i | grep "STAPM LIMIT" | awk '{print $5}')
+  PPT_LIMIT_FAST=$(sudo ryzenadj -i | grep "PPT LIMIT FAST" | awk '{print $6}')
+  PPT_LIMIT_SLOW=$(sudo ryzenadj -i | grep "PPT LIMIT SLOW" | awk '{print $7}')
+  CCLK_BOOST_SETPOINT=$(sudo ryzenadj -i | grep "CCLK Boost SETPOINT" | awk '{print $6}')
+  CCLK_BUSY_VALUE=$(sudo ryzenadj -i | grep "CCLK BUSY VALUE" | awk '{print $6}')
 
-#   printf " ${GREEN}${CPU} currrent profile info${COLOR_OFF}\n"
+  printf " ${GREEN}${CPU} currrent profile info${COLOR_OFF}\n"
 
-#   printf "BAT present: ${YELLOW}$([[ $BAT == 1 ]] && echo "YES" || echo "NO")${COLOR_OFF}\n" 
-#   printf "AC present: ${YELLOW}$([[ $AC_STATUS == 1 ]] && echo "YES" || echo "NO")${COLOR_OFF}\n" 
-#   printf "Desktop environtment: ${YELLOW}$([[ $DESKTOP == 1 ]] && echo "YES" || echo "NO")${COLOR_OFF}\n\n" 
+  printf "BAT present: ${YELLOW}$([[ $BAT == 1 ]] && echo "YES" || echo "NO")${COLOR_OFF}\n" 
+  printf "AC present: ${YELLOW}$([[ $AC_STATUS == 1 ]] && echo "YES" || echo "NO")${COLOR_OFF}\n" 
+  printf "Desktop environtment: ${YELLOW}$([[ $DESKTOP == 1 ]] && echo "YES" || echo "NO")${COLOR_OFF}\n\n" 
 
-#   printf "Param               | Description                     | Value  \n"
-#   echo "--------------------|---------------------------------|--------"
-#   printf "STAPM LIMIT         | Sustained Power Limit (mW)      | ${STAPM_LIMIT}\n"
-#   printf "PPT LIMIT SLOW      | Average Power Limit (mW)        | ${PPT_LIMIT_SLOW}\n"
-#   printf "PPT LIMIT FAST      | Actual Power Limit (mW)         | ${PPT_LIMIT_FAST}\n"
-#   printf "CCLK BOOST SETPOINT | Power Saving tune value (mW)    | ${CCLK_BOOST_SETPOINT}\n"
-#   printf "CCLK BUSY VALUE     | Max Performance tune value (mW) | ${CCLK_BUSY_VALUE}\n\n"
+  printf "Param               | Description                     | Value  \n"
+  echo "--------------------|---------------------------------|--------"
+  printf "STAPM LIMIT         | Sustained Power Limit (mW)      | ${STAPM_LIMIT}\n"
+  printf "PPT LIMIT SLOW      | Average Power Limit (mW)        | ${PPT_LIMIT_SLOW}\n"
+  printf "PPT LIMIT FAST      | Actual Power Limit (mW)         | ${PPT_LIMIT_FAST}\n"
+  printf "CCLK BOOST SETPOINT | Power Saving tune value (mW)    | ${CCLK_BOOST_SETPOINT}\n"
+  printf "CCLK BUSY VALUE     | Max Performance tune value (mW) | ${CCLK_BUSY_VALUE}\n\n"
 
-#   printf "${YELLOW}STAPM (Skin Temperature Aware Power Management)${COLOR_OFF}\n"
-#   printf "Your device's STAPM configuration is set by the manufacturer and differs depending on the processor used and the form factor of the device\n\n"
+  printf "${YELLOW}STAPM (Skin Temperature Aware Power Management)${COLOR_OFF}\n"
+  printf "Your device's STAPM configuration is set by the manufacturer and differs depending on the processor used and the form factor of the device\n\n"
 
-#   printf "${YELLOW}PPT (Package Power Tracking)${COLOR_OFF}\n"
-#   printf "PPT is a measurement of power to the CPU Socket on the motherboard and not the CPU itself\n\n"
+  printf "${YELLOW}PPT (Package Power Tracking)${COLOR_OFF}\n"
+  printf "PPT is a measurement of power to the CPU Socket on the motherboard and not the CPU itself\n\n"
 
-#   printf "${YELLOW}More info${COLOR_OFF}\n"
-#   printf "Ryzenadj: https://github.com/FlyGoat/RyzenAdj\n"
-#   printf "AMDController: https://ryzencontroller.com/\n\n"
+  printf "${YELLOW}More info${COLOR_OFF}\n"
+  printf "Ryzenadj: https://github.com/FlyGoat/RyzenAdj\n"
+  printf "AMDController: https://ryzencontroller.com/\n\n"
 
-# 	printf "${GREEN}For more help, please type 'amd-controller -h, --help'${COLOR_OFF}\n\n"
-# }
+	printf "${GREEN}For more help, please type 'amd-controller -h, --help'${COLOR_OFF}\n\n"
+}
 
-# check_dependences
+check_dependences
 
-# case $1 in
-# set)
-# 	case $2 in
-# 	-b | --base)
-# 		set_base_profile
-# 		;;
-# 	-s | --slow)
-# 		set_slow_profile
-# 		;;
-# 	-m | --medium)
-# 		set_medium_profile
-# 		;;
-# 	-h | --high)
-# 		set_high_profile
-# 		;;
-# 	-ps | --power-saving)
-# 		set_power_saving_profile
-# 		;;
-# 	-mp | --max-performance)
-# 		set_max_performance_profile
-# 		;;
-# 	*)
-# 		printf "${YELLOW}Invalid option\n${COLOR_OFF}"
-# 		help
-# 		;;
-# 	esac
-# 	;;
-# -i | --info)
-# 	show_processor_profile_info
-# 	;;
-# -h | --help)
-# 	help
-# 	;;
-# *)
-# 	printf "${YELLOW}Invalid command or option\n${COLOR_OFF}"
-# 	help
-# 	;;
-# esac
+case $1 in
+set)
+	case $2 in
+	-b | --base)
+		set_base_profile
+		;;
+	-s | --slow)
+		set_slow_profile
+		;;
+	-m | --medium)
+		set_medium_profile
+		;;
+	-h | --high)
+		set_high_profile
+		;;
+	-ps | --power-saving)
+		set_power_saving_profile
+		;;
+	-mp | --max-performance)
+		set_max_performance_profile
+		;;
+	*)
+		printf "${YELLOW}Invalid option\n${COLOR_OFF}"
+		help
+		;;
+	esac
+	;;
+-i | --info)
+	show_processor_profile_info
+	;;
+-h | --help)
+	help
+	;;
+*)
+	printf "${YELLOW}Invalid command or option\n${COLOR_OFF}"
+	help
+	;;
+esac
